version: "2"
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017
  redis:
    image: redis:alpine
    ports:
      - 6379
  locker:
    build:
      context: .
    environment:
      - MONGODB_PATH=mongodb://mongo:27017/learninglocker_v2
    links:
      - mongo
      - redis
    ports:
      - 3000:3000
